#!/usr/bin/env bash

set -eof pipefail

ROOT_DIR="${ROOT_DIR:-$(git rev-parse --show-toplevel)}"
VENDOR_FILE=${VENDOR_FILE:-"$ROOT_DIR/.go/.git-vendor"}
VENDOR_DIR=${VENDOR_DIR:-".go/.vendor/git"}
PATH=$PATH:$(git --exec-path)
# overrides location of ./go vendor add
ADD_PATH="${ADD_PATH:-}"

ADD="./go core vendor add [--prefix <path>] <name> <repository> [<ref>]"
LIST="./go core vendor list [<name>]"
REMOVE="./go core vendor remove <name>"
UPDATE="./go core vendor update <name> [<ref>] [--force]"
_usage() {
  cat <<EOF
Usage:
  ./go core vendor --help
  $ADD
  $LIST
  $REMOVE
  $UPDATE
EOF
}

case "$1" in
"" | -h | --help) _usage && exit ;;
esac

# shellcheck disable=SC1091
source git-sh-setup

require_work_tree # git-sh-setup

command="$1"
shift
case "$command" in
add | list | remove | update | init) ;;
*) echo >&2 "error: unknown command \"$command\"" && _usage && exit 1 ;;
esac

if [ "$1" = "--prefix" ]; then
  VENDOR_DIR="$2"
  shift
  shift
fi

get_repo_default() {
  local repo="$1"
  git ls-remote --symref "$repo" HEAD | tr '\n' ' ' | awk '{print $2,$4}' | sed 's#refs/.*/##'
}

get_commit() {
  local repo="$1"
  local ref="$2"
  git ls-remote "$repo" "$ref" | awk '{print $1}'
}

add() {
  require_clean_work_tree
  if [ $# -lt 2 ]; then
    die "Incorrect options provided: $ADD"
  fi
  local name="$1"
  local repo="$2"
  local ref="$3"
  local commit
  local path="$ADD_PATH"
  if [ -z "$path" ]; then
    path="$VENDOR_DIR/$(echo "$repo" | sed -E 's#^[a-zA-Z]+((://)|@)##' | sed 's#:#/#' | sed -E 's/\.git$//')"
  fi

  # check for existence of vendor file and duplicate name/path
  if [ -s "$VENDOR_FILE" ]; then
    grep -Eq "name:\s+$name" "$VENDOR_FILE" && die "name: $name already exists in git-vendor file"
    grep -Eq "path:\s+$path" "$VENDOR_FILE" && die "path: $path already exists in git-vendor file"
  fi

  # get the default HEAD reaf from the remote repo
  if [ -z "$ref" ]; then
    read -r ref commit <<<"$(get_repo_default "$repo")"
  else
    commit="$(get_commit "$repo" "$ref")"
  fi

  message=$(
    cat <<EOF
Add $name from $repo@$ref

git-vendor-name: $name
git-vendor-path: $path
git-vendor-repo: $repo
git-vendor-ref: $ref
git-vendor-commit: $commit
EOF
  )
  git subtree add --prefix "$path" "$repo" "$ref" --squash

  # append vendor file modification to same commit
  if [ ! -s "$VENDOR_FILE" ]; then
    printf "# git-vendor #\n##############\n" >"$VENDOR_FILE"
  fi
  cat <<EOF >>"$VENDOR_FILE"
{
	name:	$name
	path:	$path
	repo:	$repo
	ref:	$ref
	commit:	$commit
}
EOF
  git add "$VENDOR_FILE"
  git commit --amend --message="$message"
}

list() {
  if [ ! -s "$VENDOR_FILE" ]; then
    echo "$VENDOR_FILE" does not exist
    exit 0
  fi
  local show_only="$1"
  while read -r key val; do {
    local name
    local path
    local repo
    local ref
    local commit
    case "$key" in
    "{") unset modified name path repo ref commit ;;
    name:) name="$val" ;;
    path:) path="$val" ;;
    repo:) repo="$val" ;;
    ref:) ref="$val" ;;
    commit:) commit="$val" ;;
    "}")
      if [ "$repo" ]; then
        if [[ -z "$show_only" || "$show_only" = "$name" ]]; then
          printf '\n%s@%s:\n' "$name" "$ref"
          printf '\tpath: %s\n' "$path"
          printf '\trepo: %s\n' "$repo"
          printf '\tcommit: %s' "$commit"
          printf "\n"
        fi
      fi
      ;;
    esac
  }; done <"$VENDOR_FILE"

}

# update the git vendor file with a name and optional ref
update() {
  require_clean_work_tree
  if [ $# -lt 1 ]; then
    die "Incorrect options provided: $UPDATE"
  fi
  local name="$1"
  local update_ref
  local force
  if [[ $2 == "--force" ]]; then
    force="$2"
  else
    update_ref="$2"
    force="$3"
  fi

  local line=0
  local found
  local update_file
  local message
  # shellcheck disable=SC2094
  while read -r key val; do {
    line="$((line + 1))"
    local commit
    local commit_line
    local path
    local ref
    local ref_line
    local repo
    local update_commit
    case "$key" in
    "{") unset commit commit_line path ref_line ref repo ;;
    name:) {
      if [[ "$val" == "$name" ]]; then
        found="true"
      fi
    } ;;
    ref:) {
      ref_line="$line"
      ref="$val"
    } ;;
    repo:) repo="$val" ;;
    commit:)
      commit="$val"
      commit_line="$line"
      ;;
    path:) path="$val" ;;
    "}")
      {
        if [ -z "$found" ]; then
          continue # keep iterating if name match not found
        fi

        # Make sure the dependency exists on disk
        if [ ! -d "$path" ]; then
          die "Dependency $name is missing from $path"
        elif [ -z "$repo" ]; then
          die "Reference missing for $name"
        fi

        if [ -z "$update_ref" ]; then # if no ref was provided use one present in vendor file
          update_ref="$ref"
        fi
        update_commit="$(get_commit "$repo" "$update_ref")"
        if [[ "$update_commit" == "$commit" && "$force" != "--force" ]]; then
          echo "remote $name/$ref commit match, skipping update attempt..."
          break
        fi
        message=$(
          cat <<EOF
Update $name from $repo@$update_ref

git-vendor-name: $name
git-vendor-path: $path
git-vendor-repository: $repo
git-vendor-ref: $update_ref
git-vendor-commit: $update_commit
EOF
        )
        # replace ref if it has changed
        update_file=$(sed "${ref_line}s/^.*$/	ref:	$update_ref/" "$VENDOR_FILE" | sed "${commit_line}s/^.*$/	commit:	$update_commit/")
        break
      }
      ;;
    esac
  }; done <"$VENDOR_FILE"

  if [ -n "$update_file" ]; then
    local pre_update_commit
    pre_update_commit="$(git log -1 --format=%H)"

    {
      echo "$update_file" >"$VENDOR_FILE" &&
        rm -rf "$path" &&
        git add "$VENDOR_FILE" "$path" &&
        git commit --message "$message" --quiet &&
        git subtree add --prefix "$path" "$repo" "$update_ref" --squash &&
        git reset --soft HEAD^^ --quiet &&
        git commit --message "$message"
    } || git reset --hard "$pre_update_commit"
  fi
}

remove() {
  # require_clean_work_tree
  if [ $# -lt 1 ]; then
    die "Incorrect options provided: $REMOVE"
  fi

  local name="$1"
  local found
  local line=0
  local update_file
  local rm_path
  # shellcheck disable=SC2094
  while read -r key val; do {
    line="$((line + 1))"
    local start_line
    local end_line
    local path
    case "$key" in
    "{") start_line="$line" ;;
    name:) {
      if [[ "$val" == "$name" ]]; then
        found="true"
      fi
    } ;;
    path:) path="$val" ;;
    "}")
      end_line="$line"
      if [ -z "$found" ]; then
        continue
      fi
      # Make sure the dependency exists
      if [ ! -d "$path" ]; then
        die "Dependency $name is missing from $path"
      fi
      update_file="$(sed "${start_line},${end_line}d" "$VENDOR_FILE")"
      rm_path="$path"
      break
      ;;
    esac
  }; done <"$VENDOR_FILE"

  if [ -n "$update_file" ]; then
    echo "$update_file" >"$VENDOR_FILE"
    git add "$VENDOR_FILE"
    git rm -rf "$path"
    git commit --message "Removing $name from $rm_path"
  fi
}

# for first time dot-slash-go-setup
init() {
  local vendor="${INIT_DIR:-.vendor/git/github.com/Bestowinc/dot-slash-go}"
  add dot-slash-go https://github.com/Bestowinc/dot-slash-go
  ln -s "$vendor/.go/core" .go/core
  ln -s ".go/$vendor/go" ./go
  git add go .go
  git commit -m "added dot-slash-go-symlinks"
}

# Run the command
"$command" "$@"
